domain_path: C:\Users\joshu\Desktop\FPGA_Projects\arty_eth_echo\arty_eth_echo.sw\platform_v2\export\platform_v2\sw\standalone_ps7_cortexa9_0
app_src_dir: D:\Xilin\Vitis\2024.1\data\embeddedsw\lib\sw_apps\lwip_echo_server
template: lwip_echo_server
